<template>
  <div class="about">
    <h1>Hello There.</h1>
    <p>Please Enjoy the service</p>
    <p>You can buy me a coffee, Soon</p>
    <pre>
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMXMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWNMMxXMNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXxMX.XNdMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMk.Kd lO.KMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMx'X; xO.XMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMxOK KMkkMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXW;MMMXMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWNNNNNNNNNNNKONNNNNNNNNNNNNWMMMMMMMMMMM
MMMMMMMMMMM;                          ,k0WMMMMMMMM
MMMMMMMMMMM:                          ,'  ;XMMMMMM
MMMMMMMMMMMx                          xMWo  XMMMMM
MMMMMMMMMMMW.                        .WMMM. xMMMMM
MMMMMMMMMMMMx                        xMMMo .NMMMMM
MMMMMMMMMMMMMl                      ,Okl. 'XMMMMMM
MMMMMMMMMMMMMMo                    l;..;oKMMMMMMMM
MMMMMMMMMMMMMMM0.                .0MMMMMMMMMMMMMMM
MMMMM0OOOOOOOOOOOc..............cOOOOOOOOOOO0MMMMM
MMMMMXd:'.                              .':dNMMMMM
MMMMMMMMMMMWXKOOOOOOOOOOOOOOOOOOOOOOKXWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMM
MMMMMMWWWWNNXXKK00OOkkxxddxxkkOO00KKXXNNWWWWMMMMMM
xxxxxxxxxxxddddddddddddddddddddddddddddxxxxxxxxxxx
    </pre>
    <a href= "mailto: jay.wang@st.com">jay.wang@st.com </a><br>
    <a href= "mailto: wyj1023@gmail.com">wyj1023@gmail.com</a><br>
    <a href= "https://linkedin.com/in/youngjin-wang-b210156a">LinkedIn</a>
  </div>
</template>
